### ISSUE TITLE
16. Nodular lymphocyte predominant Hodgkin lymphoma -> Classic Hodgkin lymphoma, lymphocyte-rich type

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#204] opened 2017-03-21 18:31 UTC
From my reading, it seems like these should be disjoint classes. In the description of ORPHA:86893 Nodular lymphocyte predominant Hodgkin lymphoma, they say they do a differential diagnosis for patients and sounds like this is a different subtype.  Also this class is characterized by absence of typical Hodgkin and Reed-Sternberg (HRS) cells, which are present in ORPHA:98845 Classic Hodgkin lymphoma, lymphocyte-rich type.

Note -  looks like the [NCIT term](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=16.12d&ns=NCI_Thesaurus&code=C6914) that is part of the clique is obsoleted.

See [report](https://github.com/monarch-initiative/monarch-disease-ontology/blob/master/src/reports/new-subclass/orphanet.md#nodular-lymphocyte-predominant-hodgkin-lymphoma---classic-hodgkin-lymphoma--lymphocyte-rich-type)

![image](https://cloud.githubusercontent.com/assets/6722114/24159753/2ca39c98-0e1d-11e7-957c-91d6a6b07b0e.png)

**Comment by cmungall** [comment] 2017-03-21 20:00
Do you see the underlying cause for the problem if you look at the full graph?

**Comment by cmungall** [comment] 2017-03-21 20:00
hint: MESH is always a good place to start

**Comment by nicolevasilevsky** [comment] 2017-04-06 01:58
Looks like MeSH has a synonym 'Nodular Lymphocyte Predominant Hodgkin's Lymphoma' for Hodgkin Disease, which would suggest maybe these are equivalent, rather than subclass/parent, but that doesn't seem correct to me based on the text definitions.

**Comment by cmungall** [comment] 2017-04-11 02:06
I think the synonym is misleading but that is OK as we don't place much stock in them

the issue is here:

![image](https://cloud.githubusercontent.com/assets/50745/24889717/7d36ae1c-1e20-11e7-9149-53cc16cacfef.png)

Orphanet  calls the mapping between Orphanet:98845 and MESH:D006689 as an `E`. This is wrong. It also results in gymnastics that prevent the OMIM and Orphanet classic Hodgkins being merged (as it would result in a flip).

**Comment by pnrobinson** [comment] 2017-04-17 13:43
It is a subclass, see e.g., 
https://www.lymphomas.org.uk/about-lymphoma/types/hodgkin-lymphoma/nodular-lymphocyte-predominant-hodgkin-lymphoma-nlphl

**Comment by cmungall** [comment] 2017-04-17 16:10
@pnrobinson just to clarify, you are confirming that "Nodular lymphocyte predominant Hodgkin lymphoma" is a subclass of "Classic Hodgkin lymphoma, lymphocyte-rich type"?

**Comment by pnrobinson** [comment] 2017-04-17 16:36
sorry to be unclear!, but yes, this was a confirmation.

**Closed by pnrobinson** 2017-04-17 16:36 UTC
