### ISSUE TITLE
Review classification of Cone-Rod Dystrophy in MonDO

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#94] opened 2016-06-02 19:10 UTC
http://purl.obolibrary.org/obo/OMIM_603649

![image](https://cloud.githubusercontent.com/assets/6722114/15757928/d9ce4cd4-28bc-11e6-80b3-63904a36d99a.png)

**Comment by cmungall** [comment] 2016-06-08 04:09
I wonder if the link between leber congenital aneurosis 3 and 14 to Retinitis pigmentosa is confusing it.. these do clinically overlap

**Comment by pnrobinson** [comment] 2016-06-08 04:14
These are clinically overlapping entities
1) http://www.ncbi.nlm.nih.gov/books/NBK1298/:
While the retina may initially appear normal, a pigmentary retinopathy reminiscent of retinitis pigmentosa is frequently observed later in childhood.
2) http://www.omim.org/entry/604393
Autosomal recessive childhood-onset severe retinal dystrophy is a heterogeneous group of disorders affecting rod and cone photoreceptors simultaneously. The most severe cases are termed Leber congenital amaurosis (LCA), whereas the less aggressive forms are usually considered juvenile retinitis pigmentosa (Gu et al., 1997). 

In clinical reality the actual diagnosis given to somebody with a mutation in these genes might be either LCA or RP depending on the presentation. But I think it is useful to maintain the distinction as OMIM does.

**Comment by cmungall** [comment] 2016-06-10 14:55
this is a complicated one to figure out exactly what is going wrong here, the debug diagrams aren't helping.

For comparison, here is the ORDO classification of any term that starts "Retinitis pigmentosa' (name or syn). It strikes me as unusual, as I'd expect the generic 'Retinitis pigmentosa' to group all these

![rp](https://cloud.githubusercontent.com/assets/50745/15968401/a4536858-2ee0-11e6-8a2c-fa69306f2412.png)

**Comment by cmungall** [comment] 2016-06-10 17:25
FOUND IT!!!

Ok, this is embarassingly trivial

Here is the cause. kBOOM failed to find a solution that did not involve merging:

 MESH:C536998 ! Leber congenital amaurosis type 3
 MESH:C565814 ! Leber Congenital Amaurosis 3

But of course, these are the same!!!

Perhaps we should relax the unique name assumption at least for MESH. But really we should just do #81 first

As this is already covered by #81 I will close this

**Comment by cmungall** [comment] 2016-06-10 17:26
But just for fun, here is a visual showing each ontology, plus ontology-provided xrefs as dashed lines

![Uploading rt.png…]()

**Closed by cmungall** 2016-06-10 17:26 UTC

**Comment by cmungall** [comment] 2016-06-10 19:15
Trying again: 

![rt2](https://cloud.githubusercontent.com/assets/50745/15975767/0ea07c64-2f04-11e6-98a6-745f028eec18.png)
